# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.srcs/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2.xci
# IP: The module: 'mbdesign_axi_uartlite_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.gen/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbdesign_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.gen/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbdesign_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.gen/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbdesign_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.srcs/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2.xci
# IP: The module: 'mbdesign_axi_uartlite_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.gen/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbdesign_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.gen/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbdesign_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.gen/sources_1/bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbdesign_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
