# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/Nexys4DDR_Master.xdc

# Block Designs: bd/mbdesign/mbdesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign || ORIG_REF_NAME==mbdesign} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_microblaze_0_0/mbdesign_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_microblaze_0_0 || ORIG_REF_NAME==mbdesign_microblaze_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_dlmb_v10_0/mbdesign_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_dlmb_v10_0 || ORIG_REF_NAME==mbdesign_dlmb_v10_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_ilmb_v10_0/mbdesign_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_ilmb_v10_0 || ORIG_REF_NAME==mbdesign_ilmb_v10_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_dlmb_bram_if_cntlr_0/mbdesign_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbdesign_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_ilmb_bram_if_cntlr_0/mbdesign_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbdesign_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_lmb_bram_0/mbdesign_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_lmb_bram_0 || ORIG_REF_NAME==mbdesign_lmb_bram_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_mdm_1_0/mbdesign_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_mdm_1_0 || ORIG_REF_NAME==mbdesign_mdm_1_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_clk_wiz_1_0/mbdesign_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_clk_wiz_1_0 || ORIG_REF_NAME==mbdesign_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_rst_clk_wiz_1_100M_0/mbdesign_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mbdesign_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_axi_uartlite_0_2/mbdesign_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_axi_uartlite_0_2 || ORIG_REF_NAME==mbdesign_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_axi_timer_0_1/mbdesign_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_axi_timer_0_1 || ORIG_REF_NAME==mbdesign_axi_timer_0_1} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_dig_stopwatch_0_0/mbdesign_dig_stopwatch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_dig_stopwatch_0_0 || ORIG_REF_NAME==mbdesign_dig_stopwatch_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_xbar_0/mbdesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_xbar_0 || ORIG_REF_NAME==mbdesign_xbar_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_microblaze_0_axi_periph_1/mbdesign_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbdesign_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mbdesign_microblaze_0_axi_periph_1} -quiet] -quiet

# XDC: c:/Users/tekpun/Desktop/Microblazedigitalstopwatch/microblazedigital/microblazedigital.gen/sources_1/bd/mbdesign/mbdesign_ooc.xdc
